### ISSUE TITLE
性能监控工具nmon | 山风's blog

### ISSUE THREAD

**Issue by shanzefenglai** [shanzefenglai/shanzefenglai.github.io#7]
https://shanzefenglai.github.io/2019/04/15/%E6%80%A7%E8%83%BD%E7%9B%91%E6%8E%A7%E5%B7%A5%E5%85%B7nmon/#more 

 nmon检查安装环境1、查看版本内核1uname -a 2、查看系统版本1cat /etc/redhat-release

**Comment by paulwhr** [comment]
厉害，顶
